### PR TITLE
Fix multiple conditions parsing

### LINKED ISSUE #114: ClinVar upload issues..
From `cust002`:
image

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes:
- Fix validation error die to uppercase `multipleConditionExplanation` (fix #114 )

**How to prepare for test**:
- Download the scout submission mentioned in the issue as json and convert `MultipleConditionExplanation` to lower case

### How to test:
- Try to validate the submission against the schema using this service: https://www.jsonschemavalidator.net/

### Expected outcome:
- [x] Validation should pass

### Review:
- [ ] Code approved by
- [x] Tests executed by CR

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
After downloading the submission in question from Scout:

- Submission with uppercase (**M**ultipleConditionExplanation) 

image


- After fixing the field name with lowercase (multipleConditionExplanation):

image

The remaining error in the validation is due to one of the variants that has an empty `observedIn` field. This variant has also other issues so better fixing it before doing the submission

image

**Comment by northwestwitch** [comment]
Other errors I see in the submission:

image

image

Perhaps download it as json and inspect it before submitting it as it is?

**Comment by dnil** [comment]
> Other errors I see in the submission:
> ...
> Perhaps download it as json and inspect it before submitting it as it is?

I wonder how they got in there? Added before fixes?

**Comment by northwestwitch** [comment]
> I wonder how they got in there? Added before fixes?

The errors? Could have happened before or after. The check for what's included in the associated conditions is not that strict, even if it kind of pre-fills the field for you already (so if you stick to what's there you should be fine). I wonder if we should make it super strict instead.. Like if you add an HP term then it should have the format HP:0000356 and not HP:HP:0000356 or HP:somedisease and so on..

**Comment by dnil** [comment]
> > I wonder how they got in there? Added before fixes?
> 
> The errors? Could have happened before or after. The check for what's included in the associated conditions is not that strict, even if it kind of pre-fills the field for you already (so if you stick to what's there you should be fine). I wonder if we should make it super strict instead.. Like if you add an HP term then it should have the format HP:0000356 and not HP:HP:0000356 or HP:somedisease and so on..

Ah, ofcourse - they are manual adds?! I was wondering how they ended up there, and was searching for the events. 😆
Not wanting to be biased here, but I did see a peculiar user gender trend in the malformatted entries. 😂 We can always explain again, but I feel that with the pretty clear comment above, it would be best that manually entries are checked against our existing db entries. If we should allow manual input at all there? The submissions are brittle anyway, with little room for manual this-should-work-if-I-just-type-something-and-wish-for-it flair.

**Comment by dnil** [comment]
I'll clean up that submission, but lets fix.

**Comment by northwestwitch** [comment]
> I'll clean up that submission, but lets fix.

Agreed

**Pull request merged**
